#!/usr/bin/env bash
# Install nginx and start it
apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# Redirect to /redirect_me to a youtube video
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
